---
title: "TO 414 Project 2: Telemarketing"
author: "Brianna Patel, Taylor Hall, Yash Patel, Adam Brenner, Kaapo Andsten"
date: "2023-02-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load, Explore, and Clean Data

```{r}
tel <- read.csv("tele.csv")

tel$job <- as.factor(tel$job)
tel$marital <- as.factor(tel$marital)
tel$education <- as.factor(tel$education)
tel$default <- as.factor(tel$default)
tel$housing <- as.factor(tel$housing)
tel$loan <- as.factor(tel$loan)
tel$contact <- as.factor(tel$contact)
tel$month <- as.factor(tel$month)
tel$day_of_week <- as.factor(tel$day_of_week)
tel$poutcome <- as.factor(tel$poutcome)

tel$X <- NULL
tele$duration <- NULL
tele$pdaysdummy <- ifelse(tele$pdays == 999, 0, 1)
tele$pdays <- NULL
tel$y <- ifelse(tel$y == "yes", 1, 0)
tel$y <- as.factor(tel$y)


str(tel)
summary(tel)
```
### Test and Train

```{r}
set.seed(12345)
test_set <- sample(1:nrow(tel), .2*nrow(tel)) 

tel_train <- tel[-test_set, ]
tel_test <- tel[test_set,]
```

### Logistic Regression Model

```{r}
logisticmodel <- glm(y ~ ., data = tel_train, family = "binomial")
summary(logisticmodel)
```

```{r}
logisticprediction <- predict(logisticmodel, tel_test)

library(gmodels)
library(caret)
logisticdecision <- ifelse(logisticprediction >= .5, 1, 0)
CrossTable(logisticdecision, tel_test$y)
confusionMatrix(as.factor(logisticdecision), as.factor(tel_test$y))
```


### Normalize Data

```{r}
tel <- as.data.frame(model.matrix(~.-1, data = tel))

normalize <- function(x) {
  return ((x-min(x)) / (max(x) - min(x)))
}

tel_n <- as.data.frame(lapply(tel, normalize))
summary(tel_n)
```

### Train and Test with Normalized Data

```{r}
set.seed(12345)
test_set <- sample(1:nrow(tel_n), .2*nrow(tel_n)) 

tel_train <- tel_n[-test_set, ]
tel_test <- tel_n[test_set,]
```

### KNN Model

```{r}
library(class)
knnprediction <- knn(tel_train, tel_test, cl = tel_train$y1, k = 5)


CrossTable(knnprediction, tel_test$y1)
confusionMatrix(as.factor(knnprediction), as.factor(tel_test$y1))
```

### ANN Model

```{r}
library(neuralnet)

annmodel <- neuralnet(y1 ~ ., data = tel_train)
plot(annmodel)
```

```{r}
annprediction <- predict(annmodel, tel_test)
anndecision <- ifelse(annprediction >= .5, 1, 0)
CrossTable(anndecision, tel_test$y1)

confusionMatrix(as.factor(anndecision), as.factor(tel_test$y1))
```

### Combined Model 

```{r}
combined <- as.factor(ifelse(logisticdecision == 1 & knnprediction == 1, 1, 
                             ifelse(logisticdecision == 1 & anndecision == 1, 1, 
                                    ifelse(knnprediction == 1 & anndecision == 1, 1, 0))))

CrossTable(combined, tel_test$y1)
confusionMatrix(as.factor(combined), as.factor(tel_test$y1))
```

